project:
  type: website
  output-dir: docs
  resources:
    - assets/

website:
  title: "Andaleeb Rahman"
  favicon: assets/images/photo.jpg
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Books
        icon: book-fill
        menu:
          - href: books-social-protection.qmd
            text: Social Protection
          - href: books-food-systems.qmd
            text: Food Systems
      - href: outreach.qmd
        text: Outreach
        icon: megaphone-fill

format:
  html:
    theme: 
      light: [cosmo, styles.css]
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    anchor-sections: true

editor: visual

