project:
  type: website
  output-dir: docs
  resources:
    - assets/

website:
  title: "Andaleeb Rahman"
  favicon: assets/images/photo.jpg
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "ğŸ  Home"
      - text: "ğŸ“š Books"
        menu:
          - href: books-food-systems.qmd
            text: "Food Systems"
          - href: books-social-protection.qmd
            text: "Social Protection"
      - href: outreach.qmd
        text: "ğŸ“° Outreach"

format:
  html:
    theme: 
      light: [cosmo, styles.css]
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    anchor-sections: true

editor: visual

